config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
    # registrations: "users/registrations",
    confirmations: "users/confirmations", passwords: "users/passwords",
    password_expired: "users/password_expired"}, path: 'account', skip: [:registrations]

  root to: "daily_reports#new"
  resources :daily_reports
  get :downloads, controller: "daily_reports", action: "downloads"
  #resources :changes, :controller => 'paper_trail_manager/changes'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    patch '/account/confirmation' => 'users/confirmations#update', as: :update_user_confirmation
    get '/account/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    patch '/account' => 'users/registrations#update', :as => 'user_registration'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def always_authorize
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/edit.html.haml
- resource = (@_effective_resource || Effective::Resource.new(controller_path))
- @resource = instance_variable_get('@' + resource.name) if resource.name

- if @resource
  .row
    .col-8
      %h1= @page_title
    .col-4.text-right
      = render_resource_buttons(@resource, edit: false)

  = render_resource_form(@resource)

app/views/application/index.html.haml
- resource = (@_effective_resource || Effective::Resource.new(controller_path))

.row
  .col-8
    %h1= @page_title
  .col-4.text-right
    = render_resource_buttons(resource.klass, (action ||= :index) => false)

- if @datatable
  = render_datatable(@datatable)

- elsif instance_variable_get('@' + resource.plural_name).respond_to?(:to_partial_path)
  = render instance_variable_get('@' + resource.plural_name)

- elsif instance_variable_get('@' + resource.name).respond_to?(:to_partial_path)
  = render instance_variable_get('@' + resource.name)

- elsif Rails.env.development?
  %p effective_resources index view is not sure what to render.
  %p Define an @datatable, @#{resource.try(:plural_name) || 'a plural'}, or @#{resource.try(:name) || 'a singular'}.
  %p or include Effective::CrudController in your controller

app/views/application/new.html.haml
- resource = (@_effective_resource || Effective::Resource.new(controller_path))
- @resource = instance_variable_get('@' + resource.name) if resource.name

- if @resource
  .row
    .col-8
      %h1= @page_title
    .col-4.text-right
      = render_resource_buttons(@resource)

  = render_resource_form(@resource)

app/views/application/show.html.haml
- resource = (@_effective_resource || Effective::Resource.new(controller_path))
- @resource = instance_variable_get('@' + resource.name) if resource.name

- if @resource
  .row
    .col-8
      %h1= @page_title
    .col-4.text-right
      = render_resource_buttons(@resource, show: false)

  = render_resource_partial(@resource)

.form-actions
  = link_to 'Continue', (resource.action_path(:index) || root_path), class: 'btn btn-primary'