config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
    # registrations: "users/registrations",
    confirmations: "users/confirmations", passwords: "users/passwords",
    password_expired: "users/password_expired"}, path: 'account', skip: [:registrations]

  root to: "daily_reports#new"
  resources :daily_reports
  get :downloads, controller: "daily_reports", action: "downloads"
  #resources :changes, :controller => 'paper_trail_manager/changes'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    patch '/account/confirmation' => 'users/confirmations#update', as: :update_user_confirmation
    get '/account/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    patch '/account' => 'users/registrations#update', :as => 'user_registration'
  end
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  has_paper_trail
  belongs_to :hospital
  acts_as_xlsx :columns => ["hospital.full_name", :date,:posti_letto_totali, :posti_letto_covid_attivati, :posti_letto_covid_occupati, :posti_letto_covid_occupati_vaccinati, :posti_letto_covid_disponibili, :occupazione_posti_letto_covid, :ricoveri_covid_24h, :ricoveri_covid_24h_vaccinati, :trasferimenti_dimissioni_covid_24h, :decessi_covid_24h, :posti_letto_no_covid_attivati, :posti_letto_no_covid_occupati, :posti_letto_no_covid_disponibili, :occupazione_posti_letto_no_covid, :ricoveri_no_covid_24h, :trasferimenti_dimissioni_no_covid_24h, :decessi_no_covid_24h ], :i18n => 'activerecord.attributes'
  scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }
  #scope :weekly, -> {where(updated_at: DateTime.now.beginning_of_week..DateTime.now.end_of_week)}

  before_save :set_calculated_values

  validates :posti_letto_totali,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :posti_letto_covid_attivati,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :posti_letto_covid_occupati,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  #validates :posti_letto_covid_disponibili,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  #validates :occupazione_posti_letto_covid,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :ricoveri_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :trasferimenti_dimissioni_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :decessi_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :posti_letto_no_covid_attivati,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :posti_letto_no_covid_occupati,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  #validates :posti_letto_no_covid_disponibili,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  #validates :occupazione_posti_letto_no_covid,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :ricoveri_no_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :trasferimenti_dimissioni_no_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :decessi_no_covid_24h,  numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  validates_uniqueness_of :hospital_id, scope: :report_date, message: "Report già presente per l'ospedale e la data selezionati"
  validates_uniqueness_of :report_date, scope: :hospital_id, message: "Report già presente per l'ospedale e la data selezionati"

  def set_calculated_values
    self.posti_letto_totali = calculate_posti_letto_totali
    self.posti_letto_covid_disponibili = calculate_posti_letto_covid_disponibili
    self.posti_letto_no_covid_disponibili = calculate_posti_letto_no_covid_disponibili
    self.occupazione_posti_letto_covid = calculate_occupazione_posti_letto_covid
    self.occupazione_posti_letto_no_covid = calculate_occupazione_posti_letto_no_covid
  end

  def date
    I18n.l(report_date.to_date)
  end

  def calculate_posti_letto_totali
    posti_letto_covid_attivati.to_i + posti_letto_no_covid_attivati.to_i
  end

  def calculate_posti_letto_covid_disponibili
    posti_letto_covid_attivati.to_i - posti_letto_covid_occupati.to_i
  end

  def calculate_posti_letto_no_covid_disponibili
    posti_letto_no_covid_attivati.to_i - posti_letto_no_covid_occupati.to_i
  end

  def calculate_occupazione_posti_letto_covid
    indice = (posti_letto_covid_occupati.to_f / posti_letto_covid_attivati.to_f) * 100 rescue nil
    if indice.nan?
      return 0
    else 
      return indice.round(1)
    end
  end

  def calculate_occupazione_posti_letto_no_covid
    indice = (posti_letto_no_covid_occupati.to_f / posti_letto_no_covid_attivati.to_f) * 100 rescue nil
    if indice.nan?
      return 0
    else 
      return indice.round(1)
    end
  end
  
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: [:show, :edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json

  def downloads
    Groupdate.week_start = :monday
    respond_to do |format|
      format.xlsx {
        case params[:filter]
        when 'all'
          xlsx_package = DailyReport.joins(:hospital).order(:code, :report_date).to_xlsx
          file_name = "total_#{Time.now.to_date}"
        when 'daily'
          report_date = params[:report_date]
          file_name = "daily_#{report_date.to_date}"
          data = DailyReport.where(report_date: report_date).joins(:hospital).order(:code)
          xlsx_package = data.to_xlsx
          if params[:with_summary] == 'true'
            ws = xlsx_package.workbook.worksheets.first
            ws.add_row([""])
            ws.add_row(["","SOMMARIO"])
            ws.add_row([""])
            strutture_attive = Hospital.all.count
            rispondenza = {}
            percentuale_rispondenza = {}
            somme = {}
            medie = {}
            [:posti_letto_totali, :posti_letto_covid_attivati, :posti_letto_covid_occupati, :posti_letto_covid_occupati_vaccinati, :posti_letto_covid_disponibili, :occupazione_posti_letto_covid, :ricoveri_covid_24h, :ricoveri_covid_24h_vaccinati, :trasferimenti_dimissioni_covid_24h, :decessi_covid_24h, :posti_letto_no_covid_attivati, :posti_letto_no_covid_occupati, :posti_letto_no_covid_disponibili, :occupazione_posti_letto_no_covid, :ricoveri_no_covid_24h, :trasferimenti_dimissioni_no_covid_24h, :decessi_no_covid_24h].each do |column|
                rispondenza.merge!(column => DailyReport.where(report_date: report_date).where("#{column} is not null").count)
                percentuale_rispondenza.merge!(column => ((rispondenza[column].to_f/strutture_attive.to_f)*100).round(1))
                somme.merge!(column => data.sum(column))
                medie.merge!(column => ((somme[column].to_f/rispondenza[column].to_f).round(2)))
                
              end

            rispondenza_tsi = {}
            percentuale_rispondenza_tsi = {}
            # [:covid_posti_tsi_totali, :no_covid_posti_tsi_totali].each do |column|
            #   rispondenza_tsi.merge!(column => DailyReport.where(report_date: report_date).where("#{column} > 0").count)
              
            # end
            # [:covid_posti_tsi_totali].each do |column|
            #   somme.merge!(column => data.sum(column))
            #   medie.merge!(column => ((somme[column].to_f/DailyReport.where(report_date: report_date).where("#{column} > 0").count.to_f).round(2)))
            # end
            
            # [:covid_posti_tsi_liberi].each do |column|
            #   somme.merge!(column => data.sum(column))
            #   medie.merge!(column => ((somme[column].to_f/rispondenza_tsi[:covid_posti_tsi_totali].to_f).round(2)))
            # end
            # [:no_covid_posti_tsi_totali].each do |column|
            #   somme.merge!(column => data.sum(column))
            #   medie.merge!(column => ((somme[column].to_f/DailyReport.where(report_date: report_date).where("#{column} > 0").count.to_f).round(2)))
            # end
            # [:no_covid_posti_tsi_liberi].each do |column|
            #   somme.merge!(column => data.sum(column))
            #   medie.merge!(column => ((somme[column].to_f/rispondenza_tsi[:no_covid_posti_tsi_totali].to_f).round(2)))
            # end
            # [:tsi_posti_totali, :tsi_posti_totali_occupati].each do |column|
            #   somme.merge!(column => data.sum(column))
            #   medie.merge!(column => ((somme[column].to_f/rispondenza_tsi[:no_covid_posti_tsi_totali].to_f).round(2)))
            # end
            #medie.merge!(tsi_indice_occupazione: ((somme[:tsi_posti_totali_occupati].to_f/somme[:tsi_posti_totali].to_f)*100).round(2))
            #percentuale_rispondenza_tsi.merge!(covid_posti_tsi_totali: ((rispondenza_tsi[:covid_posti_tsi_totali].to_f/Hospital::TSI_COVID_ATTIVE.to_f)*100).round(1))
            #percentuale_rispondenza_tsi.merge!(no_covid_posti_tsi_totali: ((rispondenza_tsi[:no_covid_posti_tsi_totali].to_f/Hospital::TSI_NO_COVID_ATTIVE.to_f)*100).round(1))
            spazi =  []
            ws.add_row(["","NUMERO Strutture attive", spazi, [strutture_attive]*8, Hospital::TSI_COVID_ATTIVE, "", Hospital::TSI_NO_COVID_ATTIVE].flatten)
            ws.add_row(["","CONTA Strutture rispondenti", spazi, rispondenza.values, rispondenza_tsi[:covid_posti_tsi_totali], "", rispondenza_tsi[:no_covid_posti_tsi_totali]].flatten)
            ws.add_row(["","PERCENTUALE Strutture rispondenti", spazi, percentuale_rispondenza.values].flatten)
            ws.add_row(["","SOMMA Parametri", spazi, somme.values].flatten)
            ws.add_row(["","MEDIA Parametri", spazi, medie.values].flatten)
            ws.add_row([""])
            ws.add_row(["Strutture non rispondenti"])
            Hospital.where.not(id:  DailyReport.where(report_date: report_date).joins(:hospital).map(&:hospital_id)).each do |hospital|
              ws.add_row(["", hospital.full_name])
            end
            file_name = "daily_report_#{report_date.to_date}"
          end
          
        when 'weekly'
          weekly_data =  DailyReport.all.to_a.group_by_week{|r| r.report_date}
          
          aggregate_data = []
          weekly_data.each do |week|
            wd = {data: week.first, type: 'week'}
            daily_data = DailyReport.where(report_date: week.first..week.first+7.days).to_a.group_by_day{|r| r.report_date}
            daily_data.each do |day|
              dd = {data: day.first, type: 'day'}
              DailyReport.content_columns.each do |col|
                next if col.type == :datetime or col.type == :date or %w("occupazione_posti_letto_covid" "occupazione_posti_letto_no_covid").include? col.name
                aggregate_data << dd.merge!(I18n.t("activerecord.attributes.daily_report.#{col.name}") => day.last.sum{|d| d.send(col.name.to_sym).to_i})
              end
              occupazione_posti_letto_covid = ((dd[I18n.t("activerecord.attributes.daily_report.posti_letto_covid_occupati")].to_f / dd[I18n.t("activerecord.attributes.daily_report.posti_letto_covid_attivati")])*100).round(2)
              aggregate_data << dd.merge!(I18n.t("activerecord.attributes.daily_report.occupazione_posti_letto_covid") => occupazione_posti_letto_covid)
              occupazione_posti_letto_no_covid = ((dd[I18n.t("activerecord.attributes.daily_report.posti_letto_no_covid_occupati")].to_f / dd[I18n.t("activerecord.attributes.daily_report.posti_letto_no_covid_attivati")])*100).round(2)
              aggregate_data << dd.merge!(I18n.t("activerecord.attributes.daily_report.occupazione_posti_letto_no_covid") => occupazione_posti_letto_no_covid)
             
            end
            dd = {data: week.first}
            DailyReport.content_columns.each do |col|
              next if col.type == :datetime or col.type == :date or  %w("occupazione_posti_letto_covid" "occupazione_posti_letto_no_covid").include? col.name
              aggregate_data << wd.merge!(I18n.t("activerecord.attributes.daily_report.#{col.name}") => week.last.sum{|w| w.send(col.name.to_sym).to_i})
            end
            occupazione_posti_letto_covid = ((wd[I18n.t("activerecord.attributes.daily_report.posti_letto_covid_occupati")].to_f / wd[I18n.t("activerecord.attributes.daily_report.posti_letto_covid_attivati")])*100).round(2)
            aggregate_data << wd.merge!(I18n.t("activerecord.attributes.daily_report.occupazione_posti_letto_covid") => occupazione_posti_letto_covid)
            occupazione_posti_letto_no_covid = ((dd[I18n.t("activerecord.attributes.daily_report.posti_letto_no_covid_occupati")].to_f / wd[I18n.t("activerecord.attributes.daily_report.posti_letto_no_covid_attivati")])*100).round(2)
            aggregate_data << wd.merge!(I18n.t("activerecord.attributes.daily_report.occupazione_posti_letto_no_covid") => occupazione_posti_letto_no_covid)
          end
          aggregate_data.uniq!
          xlsx_package = Axlsx::Package.new
          wb = xlsx_package.workbook
          wb.add_worksheet do |sheet|
            sheet.add_row(aggregate_data.first.keys)
            aggregate_data.each do |week|
              sheet.add_row(week.values)
            end
            
            
          end
          file_name = "weekly_#{Time.now.to_date}"
        end
        begin 
          #temp = Tempfile.new("daily_report.xlsx") 
          #xlsx_package.serialize temp.path
          #send_file temp.path, :filename => "daily_report.xlsx", :type => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          send_data xlsx_package.to_stream.read, :filename => "#{file_name}.xlsx", :type=> "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
        ensure
          # temp.close 
          # temp.unlink
        end
      }
    end

  end

  def index
    respond_to do |format|
      format.html { 
        @daily_reports = DailyReportDatatable.new
        render :index 
      }
    end
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
  end

  # GET /daily_reports/new
  def new
    redirect_to action: :index unless current_user.write_access
    @daily_report = DailyReport.new
  end

  # GET /daily_reports/1/edit
  def edit
    redirect_to action: :index unless (current_user.hospital_ids.include? @daily_report.hospital_id and current_user.write_access)
  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/views/daily_reports/_form.html.haml
= simple_form_for(@daily_report) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .row.mb
      .col-md-6
        = f.association :hospital, label_method: 'full_name', collection: current_user.hospitals.order("city, name"), include_blank: current_user.hospitals.count > 1
    .row.mb
      .col-md-6
        = f.input :report_date, value: I18n.l(Time.now.to_date)
    .row
      -# .col-md-3
        =# f.input :posti_letto_totali calcolato
      .col-md-3  
        = f.input :posti_letto_covid_attivati
      .col-md-3
        = f.input :posti_letto_covid_occupati
      .col-md-3
        = f.input :posti_letto_covid_occupati_vaccinati  
      -# .col-md-3
        =# f.input :posti_letto_covid_disponibili. calcolato

    .row
      .col-md-3  
        = f.input :ricoveri_covid_24h
      .col-md-3  
        = f.input :ricoveri_covid_24h_vaccinati  
      .col-md-3  
        = f.input :trasferimenti_dimissioni_covid_24h
      .col-md-3  
        = f.input :decessi_covid_24h
    .row
      .col-md-3  
        = f.input :posti_letto_no_covid_attivati
      .col-md-3  
        = f.input :posti_letto_no_covid_occupati
      -# .col-md-3
        =# f.input :posti_letto_no_covid_disponibili #calcolato

      .col-md-3
    .row  
      .col-md-3 
        = f.input :ricoveri_no_covid_24h
      .col-md-3  
        = f.input :trasferimenti_dimissioni_no_covid_24h
      .col-md-3  
        = f.input :decessi_no_covid_24h
  .form-actions
    = f.button :submit, method: :put
    - unless @daily_report.new_record?
      = link_to 'Cancella il record', daily_report_path(@daily_report), class: "btn btn-primary", data: {turbolinks: false, confirm: "Sei sicuro di voler cancellare il record?" }, :method => :delete

app/views/daily_reports/edit.html.erb
<h1>Modifica <%= @daily_report.class.model_name.human %> - <span><%= @daily_report.date%></span></h1>

<%= render 'form', daily_report: @daily_report %>

<div class="mt-20">
  <%= link_to 'Visualizza', @daily_report %> |
  <%= link_to "Torna all'elenco", daily_reports_path %>
</div>

app/views/daily_reports/index.html.haml
:javascript
  function datePickerForReport(type, with_summary= false) {
    var options = {
      autoclose: true,
      language: 'it',
      format: 'yyyy-mm-dd',
      todayBtn: 'linked',
      clearBtn: true,
      todayHighlight: true
    };
    dp = $('.'+type).datepicker(options);
    dp.datepicker('show');
    
    dp.on('hide', function(e) {
      params_string = 'format=xlsx&filter=daily&with_summary='+with_summary+'&report_date='+e.date
      if(e.date == undefined) {
        return;
      }
      else {
        window.location.href = '/downloads?'+params_string
      }
      
    });

  } 


.ria_covid
  %p#notice= notice
  

  %ul.ria_covid__actions
    %li
      %i.fas.fa-download
      =link_to 'Scarica i dati giornalieri', '#' , {class: 'daily_data'}
    %li
      %i.fas.fa-download
      =link_to 'Scarica il report giornaliero','#' , {class: 'daily_report'}
    %li
      %i.fas.fa-download
      = link_to 'Scarica i dati settimanali', downloads_path(format: :xlsx, filter:'weekly')  
    %li
      %i.fas.fa-download
      = link_to 'Scarica tutto', downloads_path(format: :xlsx, filter:'all')
    - if current_user && current_user.write_access
      %li
        %i.fas.fa-plus-circle
        = link_to 'Nuovo Report giornaliero', new_daily_report_path
  
  = render_datatable(@daily_reports, input_js: { responsive: false, "oLanguage": { "sUrl": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Italian.json"}})
  

app/views/daily_reports/new.html.haml
.ria_covid
  %h1
    Nuovo report giornaliero - 
    %span #{I18n.l(Time.now.to_date)}

  = render 'form', daily_report: @daily_report
  =# link_to 'Back', daily_reports_path

app/views/daily_reports/show.html.erb
<p id="notice"><%= notice %></p>
<p class="mb-30">
<%= link_to 'Modifica', edit_daily_report_path(@daily_report) %> |
<%= link_to "Vai all'elenco", daily_reports_path %>
</p>

<%= show_for @daily_report do |daily_report| %>

  <%= daily_report.association :hospital %>
  <%= daily_report.attribute :posti_letto_totali %>
  <%= daily_report.attribute :posti_letto_covid_attivati %>
  <%= daily_report.attribute :posti_letto_covid_occupati %>
  <%= daily_report.attribute :posti_letto_covid_disponibili %>
  <%= daily_report.attribute :occupazione_posti_letto_covid %>
  <%= daily_report.attribute :ricoveri_covid_24h %>
  <%= daily_report.attribute :trasferimenti_dimissioni_covid_24h %>
  <%= daily_report.attribute :decessi_covid_24h %>
  <%= daily_report.attribute :posti_letto_no_covid_attivati %>
  <%= daily_report.attribute :posti_letto_no_covid_occupati %>
  <%= daily_report.attribute :posti_letto_no_covid_disponibili %>
  <%= daily_report.attribute :occupazione_posti_letto_no_covid %>
  <%= daily_report.attribute :ricoveri_no_covid_24h %>
  <%= daily_report.attribute :trasferimenti_dimissioni_no_covid_24h %>
  <%= daily_report.attribute :decessi_no_covid_24h %>

<% end %>

<div class="my-30">
  <%= link_to 'Modifica', edit_daily_report_path(@daily_report) %> |
  <%= link_to "Vai all'elenco", daily_reports_path %>
</div>